
setopt ALWAYS_LAST_PROMPT
setopt ALWAYS_TO_END

setopt AUTO_CD
setopt AUTO_LIST
setopt AUTO_MENU

setopt NO_MENU_COMPLETE
setopt NO_REC_EXACT

setopt AUTO_PARAM_KEYS
setopt COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
setopt NO_CORRECT
setopt CORRECT_ALL
setopt NO_EQUALS
setopt EXTENDED_GLOB
setopt HASH_CMDS
setopt HASH_DIRS

setopt BRACECCL

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt NO_HIST_NO_FUNCTIONS
setopt NO_HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY

setopt MAGIC_EQUAL_SUBST
setopt MARK_DIRS
setopt NO_MULTI_OS
setopt NO_BG_NICE
setopt NO_HUP	
setopt NO_PROMPT_CR
setopt NUMERIC_GLOB_SORT
setopt NO_PROMPT_CR
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt GLOB

setopt MULTIBYTE

setopt NO_BEEP
